// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9eShMHQiqbhQ86dWVmhWN6
// Component: doTMVq9hBpej
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 9eShMHQiqbhQ86dWVmhWN6/projectcss
import sty from "./PlasmicSignupPage12.module.css"; // plasmic-import: doTMVq9hBpej/css
import imageEp2An7L3A8C from "./images/image.png"; // plasmic-import: Ep2An7-L3a8C/picture
import icon42McrqOlBhsV3A from "./images/icon42.svg"; // plasmic-import: MCRQOlBhsV3a/picture
import vector109Ys6DepC7Wmp from "./images/vector109.svg"; // plasmic-import: YS6DepC7-Wmp/picture
import vector110DowdM9QxVPu from "./images/vector110.svg"; // plasmic-import: dowdM9QX_VPu/picture
import vector1111SrUaMjNp86 from "./images/vector111.svg"; // plasmic-import: 1Sr_UaMjNp86/picture
import vector112K8YGldQLdZhu from "./images/vector112.svg"; // plasmic-import: k8YGldQLdZhu/picture
import vector1135DiHcH4ECpbz from "./images/vector113.svg"; // plasmic-import: 5DIHcH4eCPBZ/picture
import icon43VhL4Ty2TyN8J from "./images/icon43.svg"; // plasmic-import: VhL4TY2tyN8J/picture
import vector114VowVfOkOkksh from "./images/vector114.svg"; // plasmic-import: vowVFOkOkksh/picture
import vector115EezmNgnoorVo from "./images/vector115.svg"; // plasmic-import: eezmNGNOORVo/picture
import vector116V9Ai084Dgxy from "./images/vector116.svg"; // plasmic-import: V-9AI084DGXY/picture
import vector117AwGGaik9I8Pc from "./images/vector117.svg"; // plasmic-import: awGGaik9i8Pc/picture
import vector118H189XLvQMtrN from "./images/vector118.svg"; // plasmic-import: H189xLvQMtrN/picture
import icon44U0B8CcPywn10 from "./images/icon44.svg"; // plasmic-import: u0B8ccPYWN10/picture
import vector119GpntisxQrajp from "./images/vector119.svg"; // plasmic-import: GPNTISXQrajp/picture
import vector120YUcekfnr5662 from "./images/vector120.svg"; // plasmic-import: yUcekfnr5662/picture
import vector121AADwHGb5AqPd from "./images/vector121.svg"; // plasmic-import: aADwHGb5aqPD/picture
import vector122XuSqSc9Okfi from "./images/vector122.svg"; // plasmic-import: xuSQ_sc9Okfi/picture
import vector123S8IacPcgNxSn from "./images/vector123.svg"; // plasmic-import: s8iacPcgNxSN/picture
import icon45BgjoHujRh88 from "./images/icon45.svg"; // plasmic-import: BGJOHuj-rh88/picture
import icon46VGEBsw6Th1R from "./images/icon46.svg"; // plasmic-import: vG_eBsw6TH1r/picture
import image2FbzPv3GHmqLc from "./images/image2.png"; // plasmic-import: FBZPv3GHmqLc/picture

createPlasmicElementProxy;

export const PlasmicSignupPage12__VariantProps = new Array();

export const PlasmicSignupPage12__ArgProps = new Array();

const $$ = {};

function PlasmicSignupPage12__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"signUpPage1"}
            data-plasmic-override={overrides.signUpPage1}
            className={classNames(projectcss.all, sty.signUpPage1)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___4SQa)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: imageEp2An7L3A8C,
                fullWidth: 1440,
                fullHeight: 1214,
                aspectRatio: undefined
              }}
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"frame1000004295"}
              data-plasmic-override={overrides.frame1000004295}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame1000004295)}
            >
              <div
                data-plasmic-name={"joinAThrivingCommunityOfEngineers"}
                data-plasmic-override={
                  overrides.joinAThrivingCommunityOfEngineers
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.joinAThrivingCommunityOfEngineers
                )}
              >
                {"Join a thriving community of Engineers  "}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rVjvC
                )}
              >
                {"with UnBoxing Community"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame3664"}
              data-plasmic-override={overrides.frame3664}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame3664)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"frame3662"}
                data-plasmic-override={overrides.frame3662}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame3662)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame3661"}
                  data-plasmic-override={overrides.frame3661}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame3661)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000004243"}
                    data-plasmic-override={overrides.frame1000004243}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000004243)}
                  >
                    <div
                      data-plasmic-name={"label"}
                      data-plasmic-override={overrides.label}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"Enter Last Name "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#F27312" }}
                        >
                          {"*"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame484"}
                    data-plasmic-override={overrides.frame484}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame484)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xbr2E
                      )}
                    >
                      {"Last Name"}
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"dob"}
                  data-plasmic-override={overrides.dob}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.dob)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000004244"}
                    data-plasmic-override={overrides.frame1000004244}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000004244)}
                  >
                    <div
                      data-plasmic-name={"label2"}
                      data-plasmic-override={overrides.label2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label2
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"Select DOB "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#F27312" }}
                        >
                          {"*"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3667"}
                    data-plasmic-override={overrides.frame3667}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3667)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame1000004302"}
                      data-plasmic-override={overrides.frame1000004302}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.frame1000004302
                      )}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3663"}
                        data-plasmic-override={overrides.frame3663}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3663)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eyXXf
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__apZb8)}
                            displayHeight={"24px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"24px"}
                            loading={"lazy"}
                            src={{
                              src: icon42McrqOlBhsV3A,
                              fullWidth: 24,
                              fullHeight: 24,
                              aspectRatio: 1
                            }}
                          />
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3665"}
                        data-plasmic-override={overrides.frame3665}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3665)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame1000004304"}
                          data-plasmic-override={overrides.frame1000004304}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.frame1000004304
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__q5G7
                            )}
                          >
                            {"01"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__xqa55)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector109Ys6DepC7Wmp,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__t58Ya
                            )}
                          >
                            {"02"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___7EGo6)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector110DowdM9QxVPu,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gl5XT
                            )}
                          >
                            {"03"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__dtGh3)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector1111SrUaMjNp86,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bsod6
                            )}
                          >
                            {"04"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__ySqzp)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector112K8YGldQLdZhu,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zsc2C
                            )}
                          >
                            {"05"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__dRkRx)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector1135DiHcH4ECpbz,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pkCbj
                            )}
                          >
                            {"06"}
                          </div>
                        </Stack__>
                        <div
                          data-plasmic-name={"frame1000004303"}
                          data-plasmic-override={overrides.frame1000004303}
                          className={classNames(
                            projectcss.all,
                            sty.frame1000004303
                          )}
                        >
                          <div
                            data-plasmic-name={"rectangle2523"}
                            data-plasmic-override={overrides.rectangle2523}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle2523
                            )}
                          />
                        </div>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame1000004305"}
                      data-plasmic-override={overrides.frame1000004305}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.frame1000004305
                      )}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3666"}
                        data-plasmic-override={overrides.frame3666}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3666)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fdOQl
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__ej6M6)}
                            displayHeight={"24px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"24px"}
                            loading={"lazy"}
                            src={{
                              src: icon43VhL4Ty2TyN8J,
                              fullWidth: 24,
                              fullHeight: 24,
                              aspectRatio: 1
                            }}
                          />
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3668"}
                        data-plasmic-override={overrides.frame3668}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3668)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame1000004306"}
                          data-plasmic-override={overrides.frame1000004306}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.frame1000004306
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__q5BuA
                            )}
                          >
                            {"Jan"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___709O)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector114VowVfOkOkksh,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__h2Atp
                            )}
                          >
                            {"Feb"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__k3VE4)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector115EezmNgnoorVo,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__joTvk
                            )}
                          >
                            {"Mar"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__eMcxw)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector116V9Ai084Dgxy,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cP7Ou
                            )}
                          >
                            {"Apr"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__bdFz2)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector117AwGGaik9I8Pc,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__blJss
                            )}
                          >
                            {"May"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__lms8L)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector118H189XLvQMtrN,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iJWdz
                            )}
                          >
                            {"Jun"}
                          </div>
                        </Stack__>
                        <div
                          data-plasmic-name={"frame1000004307"}
                          data-plasmic-override={overrides.frame1000004307}
                          className={classNames(
                            projectcss.all,
                            sty.frame1000004307
                          )}
                        >
                          <div
                            data-plasmic-name={"rectangle2524"}
                            data-plasmic-override={overrides.rectangle2524}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle2524
                            )}
                          />
                        </div>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame1000004308"}
                      data-plasmic-override={overrides.frame1000004308}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.frame1000004308
                      )}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3669"}
                        data-plasmic-override={overrides.frame3669}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3669)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___3Sft3
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__ik0U6)}
                            displayHeight={"24px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"24px"}
                            loading={"lazy"}
                            src={{
                              src: icon44U0B8CcPywn10,
                              fullWidth: 24,
                              fullHeight: 24,
                              aspectRatio: 1
                            }}
                          />
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3670"}
                        data-plasmic-override={overrides.frame3670}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3670)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame1000004309"}
                          data-plasmic-override={overrides.frame1000004309}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.frame1000004309
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__apEM
                            )}
                          >
                            {"2019"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__etwU3)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector119GpntisxQrajp,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sscjT
                            )}
                          >
                            {"2020"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__fucir)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector120YUcekfnr5662,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rAkYf
                            )}
                          >
                            {"2021"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__or9I)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector121AADwHGb5AqPd,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__l6EP
                            )}
                          >
                            {"2022"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__usFek)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector122XuSqSc9Okfi,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wTpjw
                            )}
                          >
                            {"2023"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__zHb65)}
                            displayHeight={"2px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100px"}
                            loading={"lazy"}
                            src={{
                              src: vector123S8IacPcgNxSn,
                              fullWidth: 100,
                              fullHeight: 2,
                              aspectRatio: 50
                            }}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gfRlj
                            )}
                          >
                            {"2024"}
                          </div>
                        </Stack__>
                        <div
                          data-plasmic-name={"frame1000004310"}
                          data-plasmic-override={overrides.frame1000004310}
                          className={classNames(
                            projectcss.all,
                            sty.frame1000004310
                          )}
                        >
                          <div
                            data-plasmic-name={"rectangle2525"}
                            data-plasmic-override={overrides.rectangle2525}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle2525
                            )}
                          />
                        </div>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"gender"}
                  data-plasmic-override={overrides.gender}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.gender)}
                >
                  <div
                    data-plasmic-name={"label3"}
                    data-plasmic-override={overrides.label3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label3
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Select Gender "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F27312" }}
                      >
                        {"*"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame488"}
                    data-plasmic-override={overrides.frame488}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame488)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ztIa3
                      )}
                    >
                      {"Gender"}
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___1Mb7O)}
                      displayHeight={"24px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"24px"}
                      loading={"lazy"}
                      src={{
                        src: icon45BgjoHujRh88,
                        fullWidth: 24,
                        fullHeight: 24,
                        aspectRatio: 1
                      }}
                    />
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"occupation"}
                  data-plasmic-override={overrides.occupation}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.occupation)}
                >
                  <div
                    data-plasmic-name={"label4"}
                    data-plasmic-override={overrides.label4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label4
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {"Select Employment Status "}
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F27312" }}
                      >
                        {"*"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame487"}
                    data-plasmic-override={overrides.frame487}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame487)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__czXaA
                      )}
                    >
                      {"Employment status"}
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__w58ZW)}
                      displayHeight={"24px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"24px"}
                      loading={"lazy"}
                      src={{
                        src: icon46VGEBsw6Th1R,
                        fullWidth: 24,
                        fullHeight: 24,
                        aspectRatio: 1
                      }}
                    />
                  </Stack__>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame3671"}
                data-plasmic-override={overrides.frame3671}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame3671)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"checkBox"}
                  data-plasmic-override={overrides.checkBox}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.checkBox)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kTe8Y
                    )}
                  >
                    {"Log into existing account"}
                  </div>
                </Stack__>
                <Stack__
                  as={"a"}
                  data-plasmic-name={"loginButton"}
                  data-plasmic-override={overrides.loginButton}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.loginButton
                  )}
                  href={`/new-page-5`}
                  target={"_blank"}
                  title={"1"}
                >
                  <div
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"Continue"}
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
            <div
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(projectcss.all, sty.logo)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"logoUbc"}
                data-plasmic-override={overrides.logoUbc}
                hasGap={true}
                className={classNames(projectcss.all, sty.logoUbc)}
              >
                <div
                  data-plasmic-name={"frame3672"}
                  data-plasmic-override={overrides.frame3672}
                  className={classNames(projectcss.all, sty.frame3672)}
                >
                  <div
                    data-plasmic-name={"c"}
                    data-plasmic-override={overrides.c}
                    className={classNames(projectcss.all, sty.c)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eRcaZ
                      )}
                    >
                      {"C"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"u"}
                    data-plasmic-override={overrides.u}
                    className={classNames(projectcss.all, sty.u)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a5O0O
                      )}
                    >
                      {"U"}
                    </div>
                  </div>
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sgbD1
                )}
              >
                {"UnBoxing Community"}
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"logo2"}
              data-plasmic-override={overrides.logo2}
              hasGap={true}
              className={classNames(projectcss.all, sty.logo2)}
            >
              <div
                data-plasmic-name={"logoUbc2"}
                data-plasmic-override={overrides.logoUbc2}
                className={classNames(projectcss.all, sty.logoUbc2)}
              >
                <div
                  data-plasmic-name={"c2"}
                  data-plasmic-override={overrides.c2}
                  className={classNames(projectcss.all, sty.c2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cGkwh
                    )}
                  >
                    {"C"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"u2"}
                  data-plasmic-override={overrides.u2}
                  className={classNames(projectcss.all, sty.u2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rFfp
                    )}
                  >
                    {"U"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iFvH
                )}
              >
                {"Back to\nUnBoxing"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame3673"}
              data-plasmic-override={overrides.frame3673}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame3673)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"frame485"}
                data-plasmic-override={overrides.frame485}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame485)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pki9S
                  )}
                >
                  {"First Name"}
                </div>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame1000004245"}
              data-plasmic-override={overrides.frame1000004245}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame1000004245)}
            >
              <div
                data-plasmic-name={"label5"}
                data-plasmic-override={overrides.label5}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.label5
                )}
              >
                <React.Fragment>
                  <React.Fragment>{"Enter First  Name "}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#F27312" }}
                  >
                    {"*"}
                  </span>
                </React.Fragment>
              </div>
            </Stack__>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__cRrg5)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: image2FbzPv3GHmqLc,
                fullWidth: 922,
                fullHeight: 26,
                aspectRatio: undefined
              }}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "signUpPage1",
    "frame1000004295",
    "joinAThrivingCommunityOfEngineers",
    "frame3664",
    "frame3662",
    "frame3661",
    "frame1000004243",
    "label",
    "frame484",
    "dob",
    "frame1000004244",
    "label2",
    "frame3667",
    "frame1000004302",
    "frame3663",
    "frame3665",
    "frame1000004304",
    "frame1000004303",
    "rectangle2523",
    "frame1000004305",
    "frame3666",
    "frame3668",
    "frame1000004306",
    "frame1000004307",
    "rectangle2524",
    "frame1000004308",
    "frame3669",
    "frame3670",
    "frame1000004309",
    "frame1000004310",
    "rectangle2525",
    "gender",
    "label3",
    "frame488",
    "occupation",
    "label4",
    "frame487",
    "frame3671",
    "checkBox",
    "loginButton",
    "button",
    "logo",
    "logoUbc",
    "frame3672",
    "c",
    "u",
    "logo2",
    "logoUbc2",
    "c2",
    "u2",
    "frame3673",
    "frame485",
    "frame1000004245",
    "label5"
  ],

  signUpPage1: [
    "signUpPage1",
    "frame1000004295",
    "joinAThrivingCommunityOfEngineers",
    "frame3664",
    "frame3662",
    "frame3661",
    "frame1000004243",
    "label",
    "frame484",
    "dob",
    "frame1000004244",
    "label2",
    "frame3667",
    "frame1000004302",
    "frame3663",
    "frame3665",
    "frame1000004304",
    "frame1000004303",
    "rectangle2523",
    "frame1000004305",
    "frame3666",
    "frame3668",
    "frame1000004306",
    "frame1000004307",
    "rectangle2524",
    "frame1000004308",
    "frame3669",
    "frame3670",
    "frame1000004309",
    "frame1000004310",
    "rectangle2525",
    "gender",
    "label3",
    "frame488",
    "occupation",
    "label4",
    "frame487",
    "frame3671",
    "checkBox",
    "loginButton",
    "button",
    "logo",
    "logoUbc",
    "frame3672",
    "c",
    "u",
    "logo2",
    "logoUbc2",
    "c2",
    "u2",
    "frame3673",
    "frame485",
    "frame1000004245",
    "label5"
  ],

  frame1000004295: ["frame1000004295", "joinAThrivingCommunityOfEngineers"],
  joinAThrivingCommunityOfEngineers: ["joinAThrivingCommunityOfEngineers"],
  frame3664: [
    "frame3664",
    "frame3662",
    "frame3661",
    "frame1000004243",
    "label",
    "frame484",
    "dob",
    "frame1000004244",
    "label2",
    "frame3667",
    "frame1000004302",
    "frame3663",
    "frame3665",
    "frame1000004304",
    "frame1000004303",
    "rectangle2523",
    "frame1000004305",
    "frame3666",
    "frame3668",
    "frame1000004306",
    "frame1000004307",
    "rectangle2524",
    "frame1000004308",
    "frame3669",
    "frame3670",
    "frame1000004309",
    "frame1000004310",
    "rectangle2525",
    "gender",
    "label3",
    "frame488",
    "occupation",
    "label4",
    "frame487",
    "frame3671",
    "checkBox",
    "loginButton",
    "button"
  ],

  frame3662: [
    "frame3662",
    "frame3661",
    "frame1000004243",
    "label",
    "frame484",
    "dob",
    "frame1000004244",
    "label2",
    "frame3667",
    "frame1000004302",
    "frame3663",
    "frame3665",
    "frame1000004304",
    "frame1000004303",
    "rectangle2523",
    "frame1000004305",
    "frame3666",
    "frame3668",
    "frame1000004306",
    "frame1000004307",
    "rectangle2524",
    "frame1000004308",
    "frame3669",
    "frame3670",
    "frame1000004309",
    "frame1000004310",
    "rectangle2525",
    "gender",
    "label3",
    "frame488",
    "occupation",
    "label4",
    "frame487"
  ],

  frame3661: ["frame3661", "frame1000004243", "label", "frame484"],
  frame1000004243: ["frame1000004243", "label"],
  label: ["label"],
  frame484: ["frame484"],
  dob: [
    "dob",
    "frame1000004244",
    "label2",
    "frame3667",
    "frame1000004302",
    "frame3663",
    "frame3665",
    "frame1000004304",
    "frame1000004303",
    "rectangle2523",
    "frame1000004305",
    "frame3666",
    "frame3668",
    "frame1000004306",
    "frame1000004307",
    "rectangle2524",
    "frame1000004308",
    "frame3669",
    "frame3670",
    "frame1000004309",
    "frame1000004310",
    "rectangle2525"
  ],

  frame1000004244: ["frame1000004244", "label2"],
  label2: ["label2"],
  frame3667: [
    "frame3667",
    "frame1000004302",
    "frame3663",
    "frame3665",
    "frame1000004304",
    "frame1000004303",
    "rectangle2523",
    "frame1000004305",
    "frame3666",
    "frame3668",
    "frame1000004306",
    "frame1000004307",
    "rectangle2524",
    "frame1000004308",
    "frame3669",
    "frame3670",
    "frame1000004309",
    "frame1000004310",
    "rectangle2525"
  ],

  frame1000004302: [
    "frame1000004302",
    "frame3663",
    "frame3665",
    "frame1000004304",
    "frame1000004303",
    "rectangle2523"
  ],

  frame3663: ["frame3663"],
  frame3665: [
    "frame3665",
    "frame1000004304",
    "frame1000004303",
    "rectangle2523"
  ],

  frame1000004304: ["frame1000004304"],
  frame1000004303: ["frame1000004303", "rectangle2523"],
  rectangle2523: ["rectangle2523"],
  frame1000004305: [
    "frame1000004305",
    "frame3666",
    "frame3668",
    "frame1000004306",
    "frame1000004307",
    "rectangle2524"
  ],

  frame3666: ["frame3666"],
  frame3668: [
    "frame3668",
    "frame1000004306",
    "frame1000004307",
    "rectangle2524"
  ],

  frame1000004306: ["frame1000004306"],
  frame1000004307: ["frame1000004307", "rectangle2524"],
  rectangle2524: ["rectangle2524"],
  frame1000004308: [
    "frame1000004308",
    "frame3669",
    "frame3670",
    "frame1000004309",
    "frame1000004310",
    "rectangle2525"
  ],

  frame3669: ["frame3669"],
  frame3670: [
    "frame3670",
    "frame1000004309",
    "frame1000004310",
    "rectangle2525"
  ],

  frame1000004309: ["frame1000004309"],
  frame1000004310: ["frame1000004310", "rectangle2525"],
  rectangle2525: ["rectangle2525"],
  gender: ["gender", "label3", "frame488"],
  label3: ["label3"],
  frame488: ["frame488"],
  occupation: ["occupation", "label4", "frame487"],
  label4: ["label4"],
  frame487: ["frame487"],
  frame3671: ["frame3671", "checkBox", "loginButton", "button"],
  checkBox: ["checkBox"],
  loginButton: ["loginButton", "button"],
  button: ["button"],
  logo: ["logo", "logoUbc", "frame3672", "c", "u"],
  logoUbc: ["logoUbc", "frame3672", "c", "u"],
  frame3672: ["frame3672", "c", "u"],
  c: ["c"],
  u: ["u"],
  logo2: ["logo2", "logoUbc2", "c2", "u2"],
  logoUbc2: ["logoUbc2", "c2", "u2"],
  c2: ["c2"],
  u2: ["u2"],
  frame3673: ["frame3673", "frame485"],
  frame485: ["frame485"],
  frame1000004245: ["frame1000004245", "label5"],
  label5: ["label5"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSignupPage12__ArgProps,
          internalVariantPropNames: PlasmicSignupPage12__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSignupPage12__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignupPage12";
  } else {
    func.displayName = `PlasmicSignupPage12.${nodeName}`;
  }
  return func;
}

export const PlasmicSignupPage12 = Object.assign(
  // Top-level PlasmicSignupPage12 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    signUpPage1: makeNodeComponent("signUpPage1"),
    frame1000004295: makeNodeComponent("frame1000004295"),
    joinAThrivingCommunityOfEngineers: makeNodeComponent(
      "joinAThrivingCommunityOfEngineers"
    ),
    frame3664: makeNodeComponent("frame3664"),
    frame3662: makeNodeComponent("frame3662"),
    frame3661: makeNodeComponent("frame3661"),
    frame1000004243: makeNodeComponent("frame1000004243"),
    label: makeNodeComponent("label"),
    frame484: makeNodeComponent("frame484"),
    dob: makeNodeComponent("dob"),
    frame1000004244: makeNodeComponent("frame1000004244"),
    label2: makeNodeComponent("label2"),
    frame3667: makeNodeComponent("frame3667"),
    frame1000004302: makeNodeComponent("frame1000004302"),
    frame3663: makeNodeComponent("frame3663"),
    frame3665: makeNodeComponent("frame3665"),
    frame1000004304: makeNodeComponent("frame1000004304"),
    frame1000004303: makeNodeComponent("frame1000004303"),
    rectangle2523: makeNodeComponent("rectangle2523"),
    frame1000004305: makeNodeComponent("frame1000004305"),
    frame3666: makeNodeComponent("frame3666"),
    frame3668: makeNodeComponent("frame3668"),
    frame1000004306: makeNodeComponent("frame1000004306"),
    frame1000004307: makeNodeComponent("frame1000004307"),
    rectangle2524: makeNodeComponent("rectangle2524"),
    frame1000004308: makeNodeComponent("frame1000004308"),
    frame3669: makeNodeComponent("frame3669"),
    frame3670: makeNodeComponent("frame3670"),
    frame1000004309: makeNodeComponent("frame1000004309"),
    frame1000004310: makeNodeComponent("frame1000004310"),
    rectangle2525: makeNodeComponent("rectangle2525"),
    gender: makeNodeComponent("gender"),
    label3: makeNodeComponent("label3"),
    frame488: makeNodeComponent("frame488"),
    occupation: makeNodeComponent("occupation"),
    label4: makeNodeComponent("label4"),
    frame487: makeNodeComponent("frame487"),
    frame3671: makeNodeComponent("frame3671"),
    checkBox: makeNodeComponent("checkBox"),
    loginButton: makeNodeComponent("loginButton"),
    button: makeNodeComponent("button"),
    logo: makeNodeComponent("logo"),
    logoUbc: makeNodeComponent("logoUbc"),
    frame3672: makeNodeComponent("frame3672"),
    c: makeNodeComponent("c"),
    u: makeNodeComponent("u"),
    logo2: makeNodeComponent("logo2"),
    logoUbc2: makeNodeComponent("logoUbc2"),
    c2: makeNodeComponent("c2"),
    u2: makeNodeComponent("u2"),
    frame3673: makeNodeComponent("frame3673"),
    frame485: makeNodeComponent("frame485"),
    frame1000004245: makeNodeComponent("frame1000004245"),
    label5: makeNodeComponent("label5"),
    // Metadata about props expected for PlasmicSignupPage12
    internalVariantProps: PlasmicSignupPage12__VariantProps,
    internalArgProps: PlasmicSignupPage12__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSignupPage12;
/* prettier-ignore-end */
