// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9eShMHQiqbhQ86dWVmhWN6
// Component: 3TkPjo5hFIGe
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 9eShMHQiqbhQ86dWVmhWN6/projectcss
import sty from "./PlasmicClickPassword.module.css"; // plasmic-import: 3TkPjo5hFIGe/css
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: wehqELmP-8wt/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: NCxh61Z_zTgr/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: Uzd0P-0NOQ-l/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: kiKzi80OG_xD/icon
import AIcon from "./icons/PlasmicIcon__A"; // plasmic-import: t5KDi-TfYURQ/icon
import imageEp2An7L3A8C from "./images/image.png"; // plasmic-import: Ep2An7-L3a8C/picture
import image2FbzPv3GHmqLc from "./images/image2.png"; // plasmic-import: FBZPv3GHmqLc/picture
import passwordHideAndSeeK4O05QbZYtV from "./images/passwordHideAndSee.svg"; // plasmic-import: _K4O05QbZYtV/picture
import passwordHideAndSee2K0CrbVpb1LTf from "./images/passwordHideAndSee2.svg"; // plasmic-import: k0crbVPB1lTF/picture
import icon28Gvx8REqcuJ1 from "./images/icon28.svg"; // plasmic-import: gvx8R_EqcuJ1/picture

createPlasmicElementProxy;

export const PlasmicClickPassword__VariantProps = new Array();

export const PlasmicClickPassword__ArgProps = new Array();

const $$ = {};

function PlasmicClickPassword__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"clickPassword"}
            data-plasmic-override={overrides.clickPassword}
            className={classNames(projectcss.all, sty.clickPassword)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__uweyP)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: imageEp2An7L3A8C,
                fullWidth: 1440,
                fullHeight: 1214,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__ouFbE)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: image2FbzPv3GHmqLc,
                fullWidth: 922,
                fullHeight: 26,
                aspectRatio: undefined
              }}
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"frame3664"}
              data-plasmic-override={overrides.frame3664}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame3664)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"frame3662"}
                data-plasmic-override={overrides.frame3662}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame3662)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame3669"}
                  data-plasmic-override={overrides.frame3669}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame3669)}
                >
                  <div
                    data-plasmic-name={"label"}
                    data-plasmic-override={overrides.label}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Enter email ID "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F37413" }}
                      >
                        {"*"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame487"}
                    data-plasmic-override={overrides.frame487}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame487)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nXk7A
                      )}
                    >
                      {"Email address"}
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame3670"}
                  data-plasmic-override={overrides.frame3670}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame3670)}
                >
                  <div
                    data-plasmic-name={"label2"}
                    data-plasmic-override={overrides.label2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label2
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Enter Password"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F37413" }}
                      >
                        {" *"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3739"}
                    data-plasmic-override={overrides.frame3739}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3739)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame488"}
                      data-plasmic-override={overrides.frame488}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame488)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__vsSju)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: passwordHideAndSeeK4O05QbZYtV,
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame3737"}
                      data-plasmic-override={overrides.frame3737}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame3737)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame489"}
                        data-plasmic-override={overrides.frame489}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame489)}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame491"}
                        data-plasmic-override={overrides.frame491}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame491)}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame490"}
                        data-plasmic-override={overrides.frame490}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame490)}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame492"}
                        data-plasmic-override={overrides.frame492}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame492)}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame493"}
                        data-plasmic-override={overrides.frame493}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame493)}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame494"}
                        data-plasmic-override={overrides.frame494}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame494)}
                      />
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame3745"}
                      data-plasmic-override={overrides.frame3745}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame3745)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oErkq
                        )}
                      >
                        {"PASSWORD MUST CONTAIN"}
                      </div>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3744"}
                        data-plasmic-override={overrides.frame3744}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3744)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame3740"}
                          data-plasmic-override={overrides.frame3740}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame3740)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vPXmK
                            )}
                          >
                            {"Between 8 and 20 characters"}
                          </div>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame3741"}
                          data-plasmic-override={overrides.frame3741}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame3741)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__d7S2Y
                            )}
                          >
                            {"1 or more upper case letters"}
                          </div>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame3742"}
                          data-plasmic-override={overrides.frame3742}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame3742)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3L8IF
                            )}
                          >
                            {"1 or more numbers"}
                          </div>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame3743"}
                          data-plasmic-override={overrides.frame3743}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame3743)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ax9Bl
                            )}
                          >
                            {"1 or more special characters"}
                          </div>
                        </Stack__>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame3671"}
                  data-plasmic-override={overrides.frame3671}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame3671)}
                >
                  <div
                    data-plasmic-name={"label3"}
                    data-plasmic-override={overrides.label3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label3
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Re-enter Password "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F37413" }}
                      >
                        {"*"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3738"}
                    data-plasmic-override={overrides.frame3738}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3738)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame495"}
                      data-plasmic-override={overrides.frame495}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame495)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lrkX5
                        )}
                      >
                        {"Confirm Password"}
                      </div>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___09Sx7)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: passwordHideAndSee2K0CrbVpb1LTf,
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </Stack__>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame3673"}
                  data-plasmic-override={overrides.frame3673}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame3673)}
                >
                  <div
                    data-plasmic-name={"label4"}
                    data-plasmic-override={overrides.label4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label4
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Enter mobile number"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F37413" }}
                      >
                        {" *"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    data-plasmic-name={"frame3672"}
                    data-plasmic-override={overrides.frame3672}
                    className={classNames(projectcss.all, sty.frame3672)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"textfield"}
                      data-plasmic-override={overrides.textfield}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.textfield)}
                    >
                      <div
                        data-plasmic-name={"indiaIn"}
                        data-plasmic-override={overrides.indiaIn}
                        className={classNames(projectcss.all, sty.indiaIn)}
                      >
                        <VectorIcon
                          className={classNames(projectcss.all, sty.svg__bj6Ay)}
                          role={"img"}
                        />

                        <VectorIcon
                          className={classNames(projectcss.all, sty.svg__mWoNg)}
                          role={"img"}
                        />

                        <VectorIcon
                          className={classNames(projectcss.all, sty.svg__elFol)}
                          role={"img"}
                        />

                        <div
                          data-plasmic-name={"frame"}
                          data-plasmic-override={overrides.frame}
                          className={classNames(projectcss.all, sty.frame)}
                        >
                          <Vector2Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dacgK
                            )}
                            role={"img"}
                          />

                          <Vector3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mwn0V
                            )}
                            role={"img"}
                          />

                          <Vector4Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__avmt
                            )}
                            role={"img"}
                          />

                          <div
                            data-plasmic-name={"d"}
                            data-plasmic-override={overrides.d}
                            className={classNames(projectcss.all, sty.d)}
                          >
                            <div
                              data-plasmic-name={"c"}
                              data-plasmic-override={overrides.c}
                              className={classNames(projectcss.all, sty.c)}
                            >
                              <div
                                data-plasmic-name={"b"}
                                data-plasmic-override={overrides.b}
                                className={classNames(projectcss.all, sty.b)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__rj99Y
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__jclw3
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"b2"}
                                data-plasmic-override={overrides.b2}
                                className={classNames(projectcss.all, sty.b2)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__ncfH
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__t2J62
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"c2"}
                              data-plasmic-override={overrides.c2}
                              className={classNames(projectcss.all, sty.c2)}
                            >
                              <div
                                data-plasmic-name={"b3"}
                                data-plasmic-override={overrides.b3}
                                className={classNames(projectcss.all, sty.b3)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__wElD8
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___4VHa8
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"b4"}
                                data-plasmic-override={overrides.b4}
                                className={classNames(projectcss.all, sty.b4)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__ljM3L
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__yNem
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"d2"}
                            data-plasmic-override={overrides.d2}
                            className={classNames(projectcss.all, sty.d2)}
                          >
                            <div
                              data-plasmic-name={"c3"}
                              data-plasmic-override={overrides.c3}
                              className={classNames(projectcss.all, sty.c3)}
                            >
                              <div
                                data-plasmic-name={"b5"}
                                data-plasmic-override={overrides.b5}
                                className={classNames(projectcss.all, sty.b5)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__rnhg7
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__c1Wqt
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"b6"}
                                data-plasmic-override={overrides.b6}
                                className={classNames(projectcss.all, sty.b6)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__mKa1
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__syH0
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"c4"}
                              data-plasmic-override={overrides.c4}
                              className={classNames(projectcss.all, sty.c4)}
                            >
                              <div
                                data-plasmic-name={"b7"}
                                data-plasmic-override={overrides.b7}
                                className={classNames(projectcss.all, sty.b7)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___6A6N
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__n3Xom
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"b8"}
                                data-plasmic-override={overrides.b8}
                                className={classNames(projectcss.all, sty.b8)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__qf5Ty
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__vJIdh
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"d3"}
                            data-plasmic-override={overrides.d3}
                            className={classNames(projectcss.all, sty.d3)}
                          >
                            <div
                              data-plasmic-name={"c5"}
                              data-plasmic-override={overrides.c5}
                              className={classNames(projectcss.all, sty.c5)}
                            >
                              <div
                                data-plasmic-name={"b9"}
                                data-plasmic-override={overrides.b9}
                                className={classNames(projectcss.all, sty.b9)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___1Jh9B
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__mrFqc
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"b10"}
                                data-plasmic-override={overrides.b10}
                                className={classNames(projectcss.all, sty.b10)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__qkcp3
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___1MeoB
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"c6"}
                              data-plasmic-override={overrides.c6}
                              className={classNames(projectcss.all, sty.c6)}
                            >
                              <div
                                data-plasmic-name={"b11"}
                                data-plasmic-override={overrides.b11}
                                className={classNames(projectcss.all, sty.b11)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__oK1N
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__tn5J
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"b12"}
                                data-plasmic-override={overrides.b12}
                                className={classNames(projectcss.all, sty.b12)}
                              >
                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__wFYhm
                                  )}
                                  role={"img"}
                                />

                                <AIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__xNg65
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__hQLV)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: icon28Gvx8REqcuJ1,
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame483"}
                      data-plasmic-override={overrides.frame483}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame483)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__seIBb
                        )}
                      >
                        {"Mobile number"}
                      </div>
                    </Stack__>
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"checkBox"}
                data-plasmic-override={overrides.checkBox}
                hasGap={true}
                className={classNames(projectcss.all, sty.checkBox)}
              >
                <div
                  data-plasmic-name={
                    "bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy"
                  }
                  data-plasmic-override={
                    overrides.bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy
                  )}
                >
                  {
                    "By Signing up, you agree to UnBoxing Community's Terms of use and Privacy Policy "
                  }
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame3666"}
                data-plasmic-override={overrides.frame3666}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame3666)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"checkBox2"}
                  data-plasmic-override={overrides.checkBox2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.checkBox2)}
                >
                  <a
                    data-plasmic-name={"link"}
                    data-plasmic-override={overrides.link}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link
                    )}
                    href={`/new-page-5`}
                    target={"_blank"}
                    title={"1"}
                  >
                    {"Back"}
                  </a>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"loginButton"}
                  data-plasmic-override={overrides.loginButton}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.loginButton)}
                >
                  <div
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"Sign Up"}
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
            <div
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(projectcss.all, sty.logo)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"logoUbc"}
                data-plasmic-override={overrides.logoUbc}
                hasGap={true}
                className={classNames(projectcss.all, sty.logoUbc)}
              >
                <div
                  data-plasmic-name={"frame3663"}
                  data-plasmic-override={overrides.frame3663}
                  className={classNames(projectcss.all, sty.frame3663)}
                >
                  <div
                    data-plasmic-name={"c7"}
                    data-plasmic-override={overrides.c7}
                    className={classNames(projectcss.all, sty.c7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mtJpO
                      )}
                    >
                      {"C"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"u"}
                    data-plasmic-override={overrides.u}
                    className={classNames(projectcss.all, sty.u)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__n18Zo
                      )}
                    >
                      {"U"}
                    </div>
                  </div>
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__l3Wl4
                )}
              >
                {"UnBoxing Community"}
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"logo2"}
              data-plasmic-override={overrides.logo2}
              hasGap={true}
              className={classNames(projectcss.all, sty.logo2)}
            >
              <div
                data-plasmic-name={"logoUbc2"}
                data-plasmic-override={overrides.logoUbc2}
                className={classNames(projectcss.all, sty.logoUbc2)}
              >
                <div
                  data-plasmic-name={"c8"}
                  data-plasmic-override={overrides.c8}
                  className={classNames(projectcss.all, sty.c8)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0PsO8
                    )}
                  >
                    {"C"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"u2"}
                  data-plasmic-override={overrides.u2}
                  className={classNames(projectcss.all, sty.u2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sWeMa
                    )}
                  >
                    {"U"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0Lpa5
                )}
              >
                {"Back to\nUnBoxing"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame1000004296"}
              data-plasmic-override={overrides.frame1000004296}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame1000004296)}
            >
              <div
                data-plasmic-name={"joinAThrivingCommunityOfEngineers"}
                data-plasmic-override={
                  overrides.joinAThrivingCommunityOfEngineers
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.joinAThrivingCommunityOfEngineers
                )}
              >
                {"Join a thriving community of Engineers  "}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__j8YO1
                )}
              >
                {"with UnBoxing Community"}
              </div>
            </Stack__>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "clickPassword",
    "frame3664",
    "frame3662",
    "frame3669",
    "label",
    "frame487",
    "frame3670",
    "label2",
    "frame3739",
    "frame488",
    "frame3737",
    "frame489",
    "frame491",
    "frame490",
    "frame492",
    "frame493",
    "frame494",
    "frame3745",
    "frame3744",
    "frame3740",
    "frame3741",
    "frame3742",
    "frame3743",
    "frame3671",
    "label3",
    "frame3738",
    "frame495",
    "frame3673",
    "label4",
    "frame3672",
    "textfield",
    "indiaIn",
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12",
    "frame483",
    "checkBox",
    "bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy",
    "frame3666",
    "checkBox2",
    "link",
    "loginButton",
    "button",
    "logo",
    "logoUbc",
    "frame3663",
    "c7",
    "u",
    "logo2",
    "logoUbc2",
    "c8",
    "u2",
    "frame1000004296",
    "joinAThrivingCommunityOfEngineers"
  ],

  clickPassword: [
    "clickPassword",
    "frame3664",
    "frame3662",
    "frame3669",
    "label",
    "frame487",
    "frame3670",
    "label2",
    "frame3739",
    "frame488",
    "frame3737",
    "frame489",
    "frame491",
    "frame490",
    "frame492",
    "frame493",
    "frame494",
    "frame3745",
    "frame3744",
    "frame3740",
    "frame3741",
    "frame3742",
    "frame3743",
    "frame3671",
    "label3",
    "frame3738",
    "frame495",
    "frame3673",
    "label4",
    "frame3672",
    "textfield",
    "indiaIn",
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12",
    "frame483",
    "checkBox",
    "bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy",
    "frame3666",
    "checkBox2",
    "link",
    "loginButton",
    "button",
    "logo",
    "logoUbc",
    "frame3663",
    "c7",
    "u",
    "logo2",
    "logoUbc2",
    "c8",
    "u2",
    "frame1000004296",
    "joinAThrivingCommunityOfEngineers"
  ],

  frame3664: [
    "frame3664",
    "frame3662",
    "frame3669",
    "label",
    "frame487",
    "frame3670",
    "label2",
    "frame3739",
    "frame488",
    "frame3737",
    "frame489",
    "frame491",
    "frame490",
    "frame492",
    "frame493",
    "frame494",
    "frame3745",
    "frame3744",
    "frame3740",
    "frame3741",
    "frame3742",
    "frame3743",
    "frame3671",
    "label3",
    "frame3738",
    "frame495",
    "frame3673",
    "label4",
    "frame3672",
    "textfield",
    "indiaIn",
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12",
    "frame483",
    "checkBox",
    "bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy",
    "frame3666",
    "checkBox2",
    "link",
    "loginButton",
    "button"
  ],

  frame3662: [
    "frame3662",
    "frame3669",
    "label",
    "frame487",
    "frame3670",
    "label2",
    "frame3739",
    "frame488",
    "frame3737",
    "frame489",
    "frame491",
    "frame490",
    "frame492",
    "frame493",
    "frame494",
    "frame3745",
    "frame3744",
    "frame3740",
    "frame3741",
    "frame3742",
    "frame3743",
    "frame3671",
    "label3",
    "frame3738",
    "frame495",
    "frame3673",
    "label4",
    "frame3672",
    "textfield",
    "indiaIn",
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12",
    "frame483"
  ],

  frame3669: ["frame3669", "label", "frame487"],
  label: ["label"],
  frame487: ["frame487"],
  frame3670: [
    "frame3670",
    "label2",
    "frame3739",
    "frame488",
    "frame3737",
    "frame489",
    "frame491",
    "frame490",
    "frame492",
    "frame493",
    "frame494",
    "frame3745",
    "frame3744",
    "frame3740",
    "frame3741",
    "frame3742",
    "frame3743"
  ],

  label2: ["label2"],
  frame3739: [
    "frame3739",
    "frame488",
    "frame3737",
    "frame489",
    "frame491",
    "frame490",
    "frame492",
    "frame493",
    "frame494",
    "frame3745",
    "frame3744",
    "frame3740",
    "frame3741",
    "frame3742",
    "frame3743"
  ],

  frame488: ["frame488"],
  frame3737: [
    "frame3737",
    "frame489",
    "frame491",
    "frame490",
    "frame492",
    "frame493",
    "frame494"
  ],

  frame489: ["frame489"],
  frame491: ["frame491"],
  frame490: ["frame490"],
  frame492: ["frame492"],
  frame493: ["frame493"],
  frame494: ["frame494"],
  frame3745: [
    "frame3745",
    "frame3744",
    "frame3740",
    "frame3741",
    "frame3742",
    "frame3743"
  ],

  frame3744: ["frame3744", "frame3740", "frame3741", "frame3742", "frame3743"],
  frame3740: ["frame3740"],
  frame3741: ["frame3741"],
  frame3742: ["frame3742"],
  frame3743: ["frame3743"],
  frame3671: ["frame3671", "label3", "frame3738", "frame495"],
  label3: ["label3"],
  frame3738: ["frame3738", "frame495"],
  frame495: ["frame495"],
  frame3673: [
    "frame3673",
    "label4",
    "frame3672",
    "textfield",
    "indiaIn",
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12",
    "frame483"
  ],

  label4: ["label4"],
  frame3672: [
    "frame3672",
    "textfield",
    "indiaIn",
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12",
    "frame483"
  ],

  textfield: [
    "textfield",
    "indiaIn",
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12"
  ],

  indiaIn: [
    "indiaIn",
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12"
  ],

  frame: [
    "frame",
    "d",
    "c",
    "b",
    "b2",
    "c2",
    "b3",
    "b4",
    "d2",
    "c3",
    "b5",
    "b6",
    "c4",
    "b7",
    "b8",
    "d3",
    "c5",
    "b9",
    "b10",
    "c6",
    "b11",
    "b12"
  ],

  d: ["d", "c", "b", "b2", "c2", "b3", "b4"],
  c: ["c", "b", "b2"],
  b: ["b"],
  b2: ["b2"],
  c2: ["c2", "b3", "b4"],
  b3: ["b3"],
  b4: ["b4"],
  d2: ["d2", "c3", "b5", "b6", "c4", "b7", "b8"],
  c3: ["c3", "b5", "b6"],
  b5: ["b5"],
  b6: ["b6"],
  c4: ["c4", "b7", "b8"],
  b7: ["b7"],
  b8: ["b8"],
  d3: ["d3", "c5", "b9", "b10", "c6", "b11", "b12"],
  c5: ["c5", "b9", "b10"],
  b9: ["b9"],
  b10: ["b10"],
  c6: ["c6", "b11", "b12"],
  b11: ["b11"],
  b12: ["b12"],
  frame483: ["frame483"],
  checkBox: [
    "checkBox",
    "bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy"
  ],

  bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy: [
    "bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy"
  ],

  frame3666: ["frame3666", "checkBox2", "link", "loginButton", "button"],
  checkBox2: ["checkBox2", "link"],
  link: ["link"],
  loginButton: ["loginButton", "button"],
  button: ["button"],
  logo: ["logo", "logoUbc", "frame3663", "c7", "u"],
  logoUbc: ["logoUbc", "frame3663", "c7", "u"],
  frame3663: ["frame3663", "c7", "u"],
  c7: ["c7"],
  u: ["u"],
  logo2: ["logo2", "logoUbc2", "c8", "u2"],
  logoUbc2: ["logoUbc2", "c8", "u2"],
  c8: ["c8"],
  u2: ["u2"],
  frame1000004296: ["frame1000004296", "joinAThrivingCommunityOfEngineers"],
  joinAThrivingCommunityOfEngineers: ["joinAThrivingCommunityOfEngineers"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicClickPassword__ArgProps,
          internalVariantPropNames: PlasmicClickPassword__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicClickPassword__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicClickPassword";
  } else {
    func.displayName = `PlasmicClickPassword.${nodeName}`;
  }
  return func;
}

export const PlasmicClickPassword = Object.assign(
  // Top-level PlasmicClickPassword renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    clickPassword: makeNodeComponent("clickPassword"),
    frame3664: makeNodeComponent("frame3664"),
    frame3662: makeNodeComponent("frame3662"),
    frame3669: makeNodeComponent("frame3669"),
    label: makeNodeComponent("label"),
    frame487: makeNodeComponent("frame487"),
    frame3670: makeNodeComponent("frame3670"),
    label2: makeNodeComponent("label2"),
    frame3739: makeNodeComponent("frame3739"),
    frame488: makeNodeComponent("frame488"),
    frame3737: makeNodeComponent("frame3737"),
    frame489: makeNodeComponent("frame489"),
    frame491: makeNodeComponent("frame491"),
    frame490: makeNodeComponent("frame490"),
    frame492: makeNodeComponent("frame492"),
    frame493: makeNodeComponent("frame493"),
    frame494: makeNodeComponent("frame494"),
    frame3745: makeNodeComponent("frame3745"),
    frame3744: makeNodeComponent("frame3744"),
    frame3740: makeNodeComponent("frame3740"),
    frame3741: makeNodeComponent("frame3741"),
    frame3742: makeNodeComponent("frame3742"),
    frame3743: makeNodeComponent("frame3743"),
    frame3671: makeNodeComponent("frame3671"),
    label3: makeNodeComponent("label3"),
    frame3738: makeNodeComponent("frame3738"),
    frame495: makeNodeComponent("frame495"),
    frame3673: makeNodeComponent("frame3673"),
    label4: makeNodeComponent("label4"),
    frame3672: makeNodeComponent("frame3672"),
    textfield: makeNodeComponent("textfield"),
    indiaIn: makeNodeComponent("indiaIn"),
    frame: makeNodeComponent("frame"),
    d: makeNodeComponent("d"),
    c: makeNodeComponent("c"),
    b: makeNodeComponent("b"),
    b2: makeNodeComponent("b2"),
    c2: makeNodeComponent("c2"),
    b3: makeNodeComponent("b3"),
    b4: makeNodeComponent("b4"),
    d2: makeNodeComponent("d2"),
    c3: makeNodeComponent("c3"),
    b5: makeNodeComponent("b5"),
    b6: makeNodeComponent("b6"),
    c4: makeNodeComponent("c4"),
    b7: makeNodeComponent("b7"),
    b8: makeNodeComponent("b8"),
    d3: makeNodeComponent("d3"),
    c5: makeNodeComponent("c5"),
    b9: makeNodeComponent("b9"),
    b10: makeNodeComponent("b10"),
    c6: makeNodeComponent("c6"),
    b11: makeNodeComponent("b11"),
    b12: makeNodeComponent("b12"),
    frame483: makeNodeComponent("frame483"),
    checkBox: makeNodeComponent("checkBox"),
    bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy:
      makeNodeComponent(
        "bySigningUpYouAgreeToUnBoxingCommunitysTermsOfUseAndPrivacyPolicy"
      ),
    frame3666: makeNodeComponent("frame3666"),
    checkBox2: makeNodeComponent("checkBox2"),
    link: makeNodeComponent("link"),
    loginButton: makeNodeComponent("loginButton"),
    button: makeNodeComponent("button"),
    logo: makeNodeComponent("logo"),
    logoUbc: makeNodeComponent("logoUbc"),
    frame3663: makeNodeComponent("frame3663"),
    c7: makeNodeComponent("c7"),
    u: makeNodeComponent("u"),
    logo2: makeNodeComponent("logo2"),
    logoUbc2: makeNodeComponent("logoUbc2"),
    c8: makeNodeComponent("c8"),
    u2: makeNodeComponent("u2"),
    frame1000004296: makeNodeComponent("frame1000004296"),
    joinAThrivingCommunityOfEngineers: makeNodeComponent(
      "joinAThrivingCommunityOfEngineers"
    ),
    // Metadata about props expected for PlasmicClickPassword
    internalVariantProps: PlasmicClickPassword__VariantProps,
    internalArgProps: PlasmicClickPassword__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicClickPassword;
/* prettier-ignore-end */
