// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9eShMHQiqbhQ86dWVmhWN6
// Component: 3cegZHqHBYP-
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 9eShMHQiqbhQ86dWVmhWN6/projectcss
import sty from "./PlasmicSignupPage11.module.css"; // plasmic-import: 3cegZHqHBYP-/css
import imageEp2An7L3A8C from "./images/image.png"; // plasmic-import: Ep2An7-L3a8C/picture
import image2FbzPv3GHmqLc from "./images/image2.png"; // plasmic-import: FBZPv3GHmqLc/picture
import icon52Dn9Kj27FRVhv from "./images/icon52.svg"; // plasmic-import: Dn9KJ27fRVhv/picture
import icon530ToMUPj4ZjU from "./images/icon53.svg"; // plasmic-import: 0ToM-uPj4ZjU/picture
import icon54QQa4BrlRtGkI from "./images/icon54.svg"; // plasmic-import: qQA4BrlRtGkI/picture
import icon55GtVtBlpddx3P from "./images/icon55.svg"; // plasmic-import: GtVTBlpddx3P/picture
import icon56LvtrBwQb6Nub from "./images/icon56.svg"; // plasmic-import: LvtrBwQb6NUB/picture

createPlasmicElementProxy;

export const PlasmicSignupPage11__VariantProps = new Array();

export const PlasmicSignupPage11__ArgProps = new Array();

const $$ = {};

function PlasmicSignupPage11__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"signUpPage1"}
            data-plasmic-override={overrides.signUpPage1}
            className={classNames(projectcss.all, sty.signUpPage1)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__fcZhi)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: imageEp2An7L3A8C,
                fullWidth: 1440,
                fullHeight: 1214,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___6SeHz)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: image2FbzPv3GHmqLc,
                fullWidth: 922,
                fullHeight: 26,
                aspectRatio: undefined
              }}
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"frame1000004295"}
              data-plasmic-override={overrides.frame1000004295}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame1000004295)}
            >
              <div
                data-plasmic-name={"joinAThrivingCommunityOfEngineers"}
                data-plasmic-override={
                  overrides.joinAThrivingCommunityOfEngineers
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.joinAThrivingCommunityOfEngineers
                )}
              >
                {"Join a thriving community of Engineers  "}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sn5Bp
                )}
              >
                {"with UnBoxing Community"}
              </div>
            </Stack__>
            <div
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(projectcss.all, sty.logo)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"logoUbc"}
                data-plasmic-override={overrides.logoUbc}
                hasGap={true}
                className={classNames(projectcss.all, sty.logoUbc)}
              >
                <div
                  data-plasmic-name={"frame3669"}
                  data-plasmic-override={overrides.frame3669}
                  className={classNames(projectcss.all, sty.frame3669)}
                >
                  <div
                    data-plasmic-name={"c"}
                    data-plasmic-override={overrides.c}
                    className={classNames(projectcss.all, sty.c)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eXhTo
                      )}
                    >
                      {"C"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"u"}
                    data-plasmic-override={overrides.u}
                    className={classNames(projectcss.all, sty.u)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pgssT
                      )}
                    >
                      {"U"}
                    </div>
                  </div>
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2LmRb
                )}
              >
                {"UnBoxing Community"}
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"logo2"}
              data-plasmic-override={overrides.logo2}
              hasGap={true}
              className={classNames(projectcss.all, sty.logo2)}
            >
              <div
                data-plasmic-name={"logoUbc2"}
                data-plasmic-override={overrides.logoUbc2}
                className={classNames(projectcss.all, sty.logoUbc2)}
              >
                <div
                  data-plasmic-name={"c2"}
                  data-plasmic-override={overrides.c2}
                  className={classNames(projectcss.all, sty.c2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__knbAn
                    )}
                  >
                    {"C"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"u2"}
                  data-plasmic-override={overrides.u2}
                  className={classNames(projectcss.all, sty.u2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rj3Ql
                    )}
                  >
                    {"U"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ouO1X
                )}
              >
                {"Back to\nUnBoxing"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame3664"}
              data-plasmic-override={overrides.frame3664}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame3664)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"frame3662"}
                data-plasmic-override={overrides.frame3662}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame3662)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame3661"}
                  data-plasmic-override={overrides.frame3661}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame3661)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000004243"}
                    data-plasmic-override={overrides.frame1000004243}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000004243)}
                  >
                    <div
                      data-plasmic-name={"label"}
                      data-plasmic-override={overrides.label}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#FFFFFF" }}
                        >
                          {"Enter First Name"}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#F27312" }}
                        >
                          {" *"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame484"}
                    data-plasmic-override={overrides.frame484}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame484)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d9ODa
                      )}
                    >
                      {"First Name"}
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame3663"}
                  data-plasmic-override={overrides.frame3663}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame3663)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000004244"}
                    data-plasmic-override={overrides.frame1000004244}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000004244)}
                  >
                    <div
                      data-plasmic-name={"label2"}
                      data-plasmic-override={overrides.label2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label2
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#FFFFFF" }}
                        >
                          {"Enter Last Name "}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#F27312", fontWeight: 700 }}
                        >
                          {"*"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame485"}
                    data-plasmic-override={overrides.frame485}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame485)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eUKmX
                      )}
                    >
                      {"Full name"}
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"dob"}
                  data-plasmic-override={overrides.dob}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.dob)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000004245"}
                    data-plasmic-override={overrides.frame1000004245}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000004245)}
                  >
                    <div
                      data-plasmic-name={"label3"}
                      data-plasmic-override={overrides.label3}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label3
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#FFFFFF" }}
                        >
                          {"Select DOB "}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#F27312" }}
                        >
                          {"*"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3667"}
                    data-plasmic-override={overrides.frame3667}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3667)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame3665"}
                      data-plasmic-override={overrides.frame3665}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame3665)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jXsTs
                        )}
                      >
                        {"Day"}
                      </div>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__uTsX8)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: icon52Dn9Kj27FRVhv,
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame3666"}
                      data-plasmic-override={overrides.frame3666}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame3666)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wSpcv
                        )}
                      >
                        {"Month"}
                      </div>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___1LbJs)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: icon530ToMUPj4ZjU,
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame3668"}
                      data-plasmic-override={overrides.frame3668}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame3668)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__l25A9
                        )}
                      >
                        {"Year"}
                      </div>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qJaoc)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: icon54QQa4BrlRtGkI,
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </Stack__>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"gender"}
                  data-plasmic-override={overrides.gender}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.gender)}
                >
                  <div
                    data-plasmic-name={"label4"}
                    data-plasmic-override={overrides.label4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label4
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {"Select Gender "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F27312" }}
                      >
                        {"*"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame488"}
                    data-plasmic-override={overrides.frame488}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame488)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vFmbx
                      )}
                    >
                      {"Gender"}
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__zpBoe)}
                      displayHeight={"24px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"24px"}
                      loading={"lazy"}
                      src={{
                        src: icon55GtVtBlpddx3P,
                        fullWidth: 24,
                        fullHeight: 24,
                        aspectRatio: 1
                      }}
                    />
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"occupation"}
                  data-plasmic-override={overrides.occupation}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.occupation)}
                >
                  <div
                    data-plasmic-name={"label5"}
                    data-plasmic-override={overrides.label5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label5
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {"Select Employment status "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F27312" }}
                      >
                        {"*"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame487"}
                    data-plasmic-override={overrides.frame487}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame487)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__niVa
                      )}
                    >
                      {"Employment status"}
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__pmSGm)}
                      displayHeight={"24px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"24px"}
                      loading={"lazy"}
                      src={{
                        src: icon56LvtrBwQb6Nub,
                        fullWidth: 24,
                        fullHeight: 24,
                        aspectRatio: 1
                      }}
                    />
                  </Stack__>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame3670"}
                data-plasmic-override={overrides.frame3670}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame3670)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"checkBox"}
                  data-plasmic-override={overrides.checkBox}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.checkBox)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rvZsk
                    )}
                  >
                    {"Log into existing account"}
                  </div>
                </Stack__>
                <Stack__
                  as={"a"}
                  data-plasmic-name={"loginButton"}
                  data-plasmic-override={overrides.loginButton}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.loginButton
                  )}
                  href={`/new-page-5`}
                  onClick={async event => {
                    const $steps = {};
                    $steps["updateStateVariable"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;
                            undefined;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateStateVariable"] != null &&
                      typeof $steps["updateStateVariable"] === "object" &&
                      typeof $steps["updateStateVariable"].then === "function"
                    ) {
                      $steps["updateStateVariable"] = await $steps[
                        "updateStateVariable"
                      ];
                    }
                  }}
                  target={"_blank"}
                  title={"1"}
                >
                  <div
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"Continue"}
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "signUpPage1",
    "frame1000004295",
    "joinAThrivingCommunityOfEngineers",
    "logo",
    "logoUbc",
    "frame3669",
    "c",
    "u",
    "logo2",
    "logoUbc2",
    "c2",
    "u2",
    "frame3664",
    "frame3662",
    "frame3661",
    "frame1000004243",
    "label",
    "frame484",
    "frame3663",
    "frame1000004244",
    "label2",
    "frame485",
    "dob",
    "frame1000004245",
    "label3",
    "frame3667",
    "frame3665",
    "frame3666",
    "frame3668",
    "gender",
    "label4",
    "frame488",
    "occupation",
    "label5",
    "frame487",
    "frame3670",
    "checkBox",
    "loginButton",
    "button"
  ],

  signUpPage1: [
    "signUpPage1",
    "frame1000004295",
    "joinAThrivingCommunityOfEngineers",
    "logo",
    "logoUbc",
    "frame3669",
    "c",
    "u",
    "logo2",
    "logoUbc2",
    "c2",
    "u2",
    "frame3664",
    "frame3662",
    "frame3661",
    "frame1000004243",
    "label",
    "frame484",
    "frame3663",
    "frame1000004244",
    "label2",
    "frame485",
    "dob",
    "frame1000004245",
    "label3",
    "frame3667",
    "frame3665",
    "frame3666",
    "frame3668",
    "gender",
    "label4",
    "frame488",
    "occupation",
    "label5",
    "frame487",
    "frame3670",
    "checkBox",
    "loginButton",
    "button"
  ],

  frame1000004295: ["frame1000004295", "joinAThrivingCommunityOfEngineers"],
  joinAThrivingCommunityOfEngineers: ["joinAThrivingCommunityOfEngineers"],
  logo: ["logo", "logoUbc", "frame3669", "c", "u"],
  logoUbc: ["logoUbc", "frame3669", "c", "u"],
  frame3669: ["frame3669", "c", "u"],
  c: ["c"],
  u: ["u"],
  logo2: ["logo2", "logoUbc2", "c2", "u2"],
  logoUbc2: ["logoUbc2", "c2", "u2"],
  c2: ["c2"],
  u2: ["u2"],
  frame3664: [
    "frame3664",
    "frame3662",
    "frame3661",
    "frame1000004243",
    "label",
    "frame484",
    "frame3663",
    "frame1000004244",
    "label2",
    "frame485",
    "dob",
    "frame1000004245",
    "label3",
    "frame3667",
    "frame3665",
    "frame3666",
    "frame3668",
    "gender",
    "label4",
    "frame488",
    "occupation",
    "label5",
    "frame487",
    "frame3670",
    "checkBox",
    "loginButton",
    "button"
  ],

  frame3662: [
    "frame3662",
    "frame3661",
    "frame1000004243",
    "label",
    "frame484",
    "frame3663",
    "frame1000004244",
    "label2",
    "frame485",
    "dob",
    "frame1000004245",
    "label3",
    "frame3667",
    "frame3665",
    "frame3666",
    "frame3668",
    "gender",
    "label4",
    "frame488",
    "occupation",
    "label5",
    "frame487"
  ],

  frame3661: ["frame3661", "frame1000004243", "label", "frame484"],
  frame1000004243: ["frame1000004243", "label"],
  label: ["label"],
  frame484: ["frame484"],
  frame3663: ["frame3663", "frame1000004244", "label2", "frame485"],
  frame1000004244: ["frame1000004244", "label2"],
  label2: ["label2"],
  frame485: ["frame485"],
  dob: [
    "dob",
    "frame1000004245",
    "label3",
    "frame3667",
    "frame3665",
    "frame3666",
    "frame3668"
  ],

  frame1000004245: ["frame1000004245", "label3"],
  label3: ["label3"],
  frame3667: ["frame3667", "frame3665", "frame3666", "frame3668"],
  frame3665: ["frame3665"],
  frame3666: ["frame3666"],
  frame3668: ["frame3668"],
  gender: ["gender", "label4", "frame488"],
  label4: ["label4"],
  frame488: ["frame488"],
  occupation: ["occupation", "label5", "frame487"],
  label5: ["label5"],
  frame487: ["frame487"],
  frame3670: ["frame3670", "checkBox", "loginButton", "button"],
  checkBox: ["checkBox"],
  loginButton: ["loginButton", "button"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSignupPage11__ArgProps,
          internalVariantPropNames: PlasmicSignupPage11__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSignupPage11__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignupPage11";
  } else {
    func.displayName = `PlasmicSignupPage11.${nodeName}`;
  }
  return func;
}

export const PlasmicSignupPage11 = Object.assign(
  // Top-level PlasmicSignupPage11 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    signUpPage1: makeNodeComponent("signUpPage1"),
    frame1000004295: makeNodeComponent("frame1000004295"),
    joinAThrivingCommunityOfEngineers: makeNodeComponent(
      "joinAThrivingCommunityOfEngineers"
    ),
    logo: makeNodeComponent("logo"),
    logoUbc: makeNodeComponent("logoUbc"),
    frame3669: makeNodeComponent("frame3669"),
    c: makeNodeComponent("c"),
    u: makeNodeComponent("u"),
    logo2: makeNodeComponent("logo2"),
    logoUbc2: makeNodeComponent("logoUbc2"),
    c2: makeNodeComponent("c2"),
    u2: makeNodeComponent("u2"),
    frame3664: makeNodeComponent("frame3664"),
    frame3662: makeNodeComponent("frame3662"),
    frame3661: makeNodeComponent("frame3661"),
    frame1000004243: makeNodeComponent("frame1000004243"),
    label: makeNodeComponent("label"),
    frame484: makeNodeComponent("frame484"),
    frame3663: makeNodeComponent("frame3663"),
    frame1000004244: makeNodeComponent("frame1000004244"),
    label2: makeNodeComponent("label2"),
    frame485: makeNodeComponent("frame485"),
    dob: makeNodeComponent("dob"),
    frame1000004245: makeNodeComponent("frame1000004245"),
    label3: makeNodeComponent("label3"),
    frame3667: makeNodeComponent("frame3667"),
    frame3665: makeNodeComponent("frame3665"),
    frame3666: makeNodeComponent("frame3666"),
    frame3668: makeNodeComponent("frame3668"),
    gender: makeNodeComponent("gender"),
    label4: makeNodeComponent("label4"),
    frame488: makeNodeComponent("frame488"),
    occupation: makeNodeComponent("occupation"),
    label5: makeNodeComponent("label5"),
    frame487: makeNodeComponent("frame487"),
    frame3670: makeNodeComponent("frame3670"),
    checkBox: makeNodeComponent("checkBox"),
    loginButton: makeNodeComponent("loginButton"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicSignupPage11
    internalVariantProps: PlasmicSignupPage11__VariantProps,
    internalArgProps: PlasmicSignupPage11__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSignupPage11;
/* prettier-ignore-end */
