// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9eShMHQiqbhQ86dWVmhWN6
// Component: esyft2uHAHt0
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 9eShMHQiqbhQ86dWVmhWN6/projectcss
import sty from "./PlasmicOtpSee.module.css"; // plasmic-import: esyft2uHAHt0/css
import imageEp2An7L3A8C from "./images/image.png"; // plasmic-import: Ep2An7-L3a8C/picture
import passwordHideAndSee5RRNtJPxZdlI from "./images/passwordHideAndSee5.svg"; // plasmic-import: rRNtJPx-ZdlI/picture
import image2FbzPv3GHmqLc from "./images/image2.png"; // plasmic-import: FBZPv3GHmqLc/picture

createPlasmicElementProxy;

export const PlasmicOtpSee__VariantProps = new Array();

export const PlasmicOtpSee__ArgProps = new Array();

const $$ = {};

function PlasmicOtpSee__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"otp"}
            data-plasmic-override={overrides.otp}
            className={classNames(projectcss.all, sty.otp)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__q7JX)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: imageEp2An7L3A8C,
                fullWidth: 1440,
                fullHeight: 1214,
                aspectRatio: undefined
              }}
            />

            <div
              data-plasmic-name={"joinAThrivingCommunityOfEngineers"}
              data-plasmic-override={
                overrides.joinAThrivingCommunityOfEngineers
              }
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.joinAThrivingCommunityOfEngineers
              )}
            >
              {"Join a thriving community of Engineers  "}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kj2RE
              )}
            >
              {"with UnBoxing Community"}
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame3664"}
              data-plasmic-override={overrides.frame3664}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame3664)}
            >
              <div
                data-plasmic-name={"checkBox"}
                data-plasmic-override={overrides.checkBox}
                className={classNames(projectcss.all, sty.checkBox)}
              >
                <div
                  data-plasmic-name={"weHaveSentYouA4DigitOtp"}
                  data-plasmic-override={overrides.weHaveSentYouA4DigitOtp}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.weHaveSentYouA4DigitOtp
                  )}
                >
                  {"We have sent you a 4-digit OTP "}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"checkBox2"}
                  data-plasmic-override={overrides.checkBox2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.checkBox2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qqKbI
                    )}
                  >
                    {"to +91-9876 543 210"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t0Jg2
                    )}
                  >
                    {"Resend OTP?"}
                  </div>
                </Stack__>
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"otp2"}
                data-plasmic-override={overrides.otp2}
                hasGap={true}
                className={classNames(projectcss.all, sty.otp2)}
              >
                <div
                  data-plasmic-name={"frame3666"}
                  data-plasmic-override={overrides.frame3666}
                  className={classNames(projectcss.all, sty.frame3666)}
                >
                  <div
                    data-plasmic-name={"label"}
                    data-plasmic-override={overrides.label}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F7F7F7" }}
                      >
                        {"Enter OTP"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F27312" }}
                      >
                        {" * "}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3667"}
                    data-plasmic-override={overrides.frame3667}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3667)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame3752"}
                      data-plasmic-override={overrides.frame3752}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame3752)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3662"}
                        data-plasmic-override={overrides.frame3662}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3662)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dWzJq
                          )}
                        >
                          {"1"}
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3663"}
                        data-plasmic-override={overrides.frame3663}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3663)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xCii
                          )}
                        >
                          {"2"}
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3665"}
                        data-plasmic-override={overrides.frame3665}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3665)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pl9Zl
                          )}
                        >
                          {"3"}
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame3668"}
                        data-plasmic-override={overrides.frame3668}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame3668)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qnWXq
                          )}
                        >
                          {"4"}
                        </div>
                      </Stack__>
                    </Stack__>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__veArN)}
                      displayHeight={"24px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"24px"}
                      loading={"lazy"}
                      src={{
                        src: passwordHideAndSee5RRNtJPxZdlI,
                        fullWidth: 24,
                        fullHeight: 24,
                        aspectRatio: 1
                      }}
                    />
                  </Stack__>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame3669"}
                data-plasmic-override={overrides.frame3669}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame3669)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"checkBox3"}
                  data-plasmic-override={overrides.checkBox3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.checkBox3)}
                >
                  <a
                    data-plasmic-name={"link"}
                    data-plasmic-override={overrides.link}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link
                    )}
                    href={`/new-page-7`}
                    target={"_blank"}
                    title={"1"}
                  >
                    {"Back"}
                  </a>
                </Stack__>
                <Stack__
                  as={"a"}
                  data-plasmic-name={"loginButton"}
                  data-plasmic-override={overrides.loginButton}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.loginButton
                  )}
                  href={`/new-page-12`}
                  target={"_blank"}
                  title={"1"}
                >
                  <div
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"Verify"}
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
            <div
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(projectcss.all, sty.logo)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"logoUbc"}
                data-plasmic-override={overrides.logoUbc}
                hasGap={true}
                className={classNames(projectcss.all, sty.logoUbc)}
              >
                <div
                  data-plasmic-name={"frame3670"}
                  data-plasmic-override={overrides.frame3670}
                  className={classNames(projectcss.all, sty.frame3670)}
                >
                  <div
                    data-plasmic-name={"c"}
                    data-plasmic-override={overrides.c}
                    className={classNames(projectcss.all, sty.c)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__z9Lg2
                      )}
                    >
                      {"C"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"u"}
                    data-plasmic-override={overrides.u}
                    className={classNames(projectcss.all, sty.u)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2Td2N
                      )}
                    >
                      {"U"}
                    </div>
                  </div>
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ja4Wk
                )}
              >
                {"UnBoxing Community"}
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"logo2"}
              data-plasmic-override={overrides.logo2}
              hasGap={true}
              className={classNames(projectcss.all, sty.logo2)}
            >
              <div
                data-plasmic-name={"logoUbc2"}
                data-plasmic-override={overrides.logoUbc2}
                className={classNames(projectcss.all, sty.logoUbc2)}
              >
                <div
                  data-plasmic-name={"c2"}
                  data-plasmic-override={overrides.c2}
                  className={classNames(projectcss.all, sty.c2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wEzc5
                    )}
                  >
                    {"C"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"u2"}
                  data-plasmic-override={overrides.u2}
                  className={classNames(projectcss.all, sty.u2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qtqzS
                    )}
                  >
                    {"U"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iyRng
                )}
              >
                {"Back to\nUnBoxing"}
              </div>
            </Stack__>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__jBhPn)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: image2FbzPv3GHmqLc,
                fullWidth: 922,
                fullHeight: 26,
                aspectRatio: undefined
              }}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "otp",
    "joinAThrivingCommunityOfEngineers",
    "frame3664",
    "checkBox",
    "weHaveSentYouA4DigitOtp",
    "checkBox2",
    "otp2",
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "frame3662",
    "frame3663",
    "frame3665",
    "frame3668",
    "frame3669",
    "checkBox3",
    "link",
    "loginButton",
    "button",
    "logo",
    "logoUbc",
    "frame3670",
    "c",
    "u",
    "logo2",
    "logoUbc2",
    "c2",
    "u2"
  ],

  otp: [
    "otp",
    "joinAThrivingCommunityOfEngineers",
    "frame3664",
    "checkBox",
    "weHaveSentYouA4DigitOtp",
    "checkBox2",
    "otp2",
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "frame3662",
    "frame3663",
    "frame3665",
    "frame3668",
    "frame3669",
    "checkBox3",
    "link",
    "loginButton",
    "button",
    "logo",
    "logoUbc",
    "frame3670",
    "c",
    "u",
    "logo2",
    "logoUbc2",
    "c2",
    "u2"
  ],

  joinAThrivingCommunityOfEngineers: ["joinAThrivingCommunityOfEngineers"],
  frame3664: [
    "frame3664",
    "checkBox",
    "weHaveSentYouA4DigitOtp",
    "checkBox2",
    "otp2",
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "frame3662",
    "frame3663",
    "frame3665",
    "frame3668",
    "frame3669",
    "checkBox3",
    "link",
    "loginButton",
    "button"
  ],

  checkBox: ["checkBox", "weHaveSentYouA4DigitOtp", "checkBox2"],
  weHaveSentYouA4DigitOtp: ["weHaveSentYouA4DigitOtp"],
  checkBox2: ["checkBox2"],
  otp2: [
    "otp2",
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "frame3662",
    "frame3663",
    "frame3665",
    "frame3668"
  ],

  frame3666: [
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "frame3662",
    "frame3663",
    "frame3665",
    "frame3668"
  ],

  label: ["label"],
  frame3667: [
    "frame3667",
    "frame3752",
    "frame3662",
    "frame3663",
    "frame3665",
    "frame3668"
  ],

  frame3752: ["frame3752", "frame3662", "frame3663", "frame3665", "frame3668"],
  frame3662: ["frame3662"],
  frame3663: ["frame3663"],
  frame3665: ["frame3665"],
  frame3668: ["frame3668"],
  frame3669: ["frame3669", "checkBox3", "link", "loginButton", "button"],
  checkBox3: ["checkBox3", "link"],
  link: ["link"],
  loginButton: ["loginButton", "button"],
  button: ["button"],
  logo: ["logo", "logoUbc", "frame3670", "c", "u"],
  logoUbc: ["logoUbc", "frame3670", "c", "u"],
  frame3670: ["frame3670", "c", "u"],
  c: ["c"],
  u: ["u"],
  logo2: ["logo2", "logoUbc2", "c2", "u2"],
  logoUbc2: ["logoUbc2", "c2", "u2"],
  c2: ["c2"],
  u2: ["u2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOtpSee__ArgProps,
          internalVariantPropNames: PlasmicOtpSee__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOtpSee__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOtpSee";
  } else {
    func.displayName = `PlasmicOtpSee.${nodeName}`;
  }
  return func;
}

export const PlasmicOtpSee = Object.assign(
  // Top-level PlasmicOtpSee renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    otp: makeNodeComponent("otp"),
    joinAThrivingCommunityOfEngineers: makeNodeComponent(
      "joinAThrivingCommunityOfEngineers"
    ),
    frame3664: makeNodeComponent("frame3664"),
    checkBox: makeNodeComponent("checkBox"),
    weHaveSentYouA4DigitOtp: makeNodeComponent("weHaveSentYouA4DigitOtp"),
    checkBox2: makeNodeComponent("checkBox2"),
    otp2: makeNodeComponent("otp2"),
    frame3666: makeNodeComponent("frame3666"),
    label: makeNodeComponent("label"),
    frame3667: makeNodeComponent("frame3667"),
    frame3752: makeNodeComponent("frame3752"),
    frame3662: makeNodeComponent("frame3662"),
    frame3663: makeNodeComponent("frame3663"),
    frame3665: makeNodeComponent("frame3665"),
    frame3668: makeNodeComponent("frame3668"),
    frame3669: makeNodeComponent("frame3669"),
    checkBox3: makeNodeComponent("checkBox3"),
    link: makeNodeComponent("link"),
    loginButton: makeNodeComponent("loginButton"),
    button: makeNodeComponent("button"),
    logo: makeNodeComponent("logo"),
    logoUbc: makeNodeComponent("logoUbc"),
    frame3670: makeNodeComponent("frame3670"),
    c: makeNodeComponent("c"),
    u: makeNodeComponent("u"),
    logo2: makeNodeComponent("logo2"),
    logoUbc2: makeNodeComponent("logoUbc2"),
    c2: makeNodeComponent("c2"),
    u2: makeNodeComponent("u2"),
    // Metadata about props expected for PlasmicOtpSee
    internalVariantProps: PlasmicOtpSee__VariantProps,
    internalArgProps: PlasmicOtpSee__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicOtpSee;
/* prettier-ignore-end */
