// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9eShMHQiqbhQ86dWVmhWN6
// Component: PJWTlzHcBZ7p
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 9eShMHQiqbhQ86dWVmhWN6/projectcss
import sty from "./PlasmicOtp.module.css"; // plasmic-import: PJWTlzHcBZ7p/css
import Group1Icon from "./icons/PlasmicIcon__Group1"; // plasmic-import: qRfkE60ftApl/icon
import imageEp2An7L3A8C from "./images/image.png"; // plasmic-import: Ep2An7-L3a8C/picture
import frame3662HiGuiSudckdF from "./images/frame3662.svg"; // plasmic-import: hiGuiSudckdF/picture
import frame3663Sy0TYaZ5AgvX from "./images/frame3663.svg"; // plasmic-import: sy0TYaZ5agvX/picture
import frame3665KyG6XWMxv28U from "./images/frame3665.svg"; // plasmic-import: KyG6xWMxv28u/picture
import frame3664EncRd3ROrvgW from "./images/frame3664.svg"; // plasmic-import: encRD3rOrvgW/picture
import image2FbzPv3GHmqLc from "./images/image2.png"; // plasmic-import: FBZPv3GHmqLc/picture

createPlasmicElementProxy;

export const PlasmicOtp__VariantProps = new Array();

export const PlasmicOtp__ArgProps = new Array();

const $$ = {};

function PlasmicOtp__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"otp"}
            data-plasmic-override={overrides.otp}
            className={classNames(projectcss.all, sty.otp)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__wJYga)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: imageEp2An7L3A8C,
                fullWidth: 1440,
                fullHeight: 1214,
                aspectRatio: undefined
              }}
            />

            <div
              data-plasmic-name={"joinAThrivingCommunityOfEngineers"}
              data-plasmic-override={
                overrides.joinAThrivingCommunityOfEngineers
              }
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.joinAThrivingCommunityOfEngineers
              )}
            >
              {"Join a thriving community of Engineers  "}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kpgca
              )}
            >
              {"with UnBoxing Community"}
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame3664"}
              data-plasmic-override={overrides.frame3664}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame3664)}
            >
              <div
                data-plasmic-name={"checkBox"}
                data-plasmic-override={overrides.checkBox}
                className={classNames(projectcss.all, sty.checkBox)}
              >
                <div
                  data-plasmic-name={"weHaveSentYouA4DigitOtp"}
                  data-plasmic-override={overrides.weHaveSentYouA4DigitOtp}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.weHaveSentYouA4DigitOtp
                  )}
                >
                  {"We have sent you a 4-digit OTP "}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"checkBox2"}
                  data-plasmic-override={overrides.checkBox2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.checkBox2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fsxfk
                    )}
                  >
                    {"to +91-9876 543 210"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sr5FQ
                    )}
                  >
                    {"Resend OTP?"}
                  </div>
                </Stack__>
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"otp2"}
                data-plasmic-override={overrides.otp2}
                hasGap={true}
                className={classNames(projectcss.all, sty.otp2)}
              >
                <div
                  data-plasmic-name={"frame3666"}
                  data-plasmic-override={overrides.frame3666}
                  className={classNames(projectcss.all, sty.frame3666)}
                >
                  <div
                    data-plasmic-name={"label"}
                    data-plasmic-override={overrides.label}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Enter OTP "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#F37413" }}
                      >
                        {"*"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3667"}
                    data-plasmic-override={overrides.frame3667}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3667)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame3752"}
                      data-plasmic-override={overrides.frame3752}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame3752)}
                    >
                      <Stack__
                        as={PlasmicImg__}
                        hasGap={true}
                        alt={""}
                        className={classNames(sty.img__cnLei)}
                        displayHeight={"50px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"50px"}
                        loading={"lazy"}
                        src={{
                          src: frame3662HiGuiSudckdF,
                          fullWidth: 50,
                          fullHeight: 50,
                          aspectRatio: 1
                        }}
                      />

                      <Stack__
                        as={PlasmicImg__}
                        hasGap={true}
                        alt={""}
                        className={classNames(sty.img___55Wy8)}
                        displayHeight={"50px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"50px"}
                        loading={"lazy"}
                        src={{
                          src: frame3663Sy0TYaZ5AgvX,
                          fullWidth: 50,
                          fullHeight: 50,
                          aspectRatio: 1
                        }}
                      />

                      <Stack__
                        as={PlasmicImg__}
                        hasGap={true}
                        alt={""}
                        className={classNames(sty.img___0ZVoN)}
                        displayHeight={"50px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"50px"}
                        loading={"lazy"}
                        src={{
                          src: frame3665KyG6XWMxv28U,
                          fullWidth: 50,
                          fullHeight: 50,
                          aspectRatio: 1
                        }}
                      />

                      <Stack__
                        as={PlasmicImg__}
                        hasGap={true}
                        alt={""}
                        className={classNames(sty.img__uswKn)}
                        displayHeight={"50px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"50px"}
                        loading={"lazy"}
                        src={{
                          src: frame3664EncRd3ROrvgW,
                          fullWidth: 50,
                          fullHeight: 50,
                          aspectRatio: 1
                        }}
                      />
                    </Stack__>
                    <div
                      data-plasmic-name={"passwordHideAndSee"}
                      data-plasmic-override={overrides.passwordHideAndSee}
                      className={classNames(
                        projectcss.all,
                        sty.passwordHideAndSee
                      )}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link___0W4Nn
                        )}
                      >
                        <Group1Icon
                          data-plasmic-name={"svg"}
                          data-plasmic-override={overrides.svg}
                          className={classNames(projectcss.all, sty.svg)}
                          role={"img"}
                        />
                      </a>
                    </div>
                  </Stack__>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame3665"}
                data-plasmic-override={overrides.frame3665}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame3665)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"checkBox3"}
                  data-plasmic-override={overrides.checkBox3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.checkBox3)}
                >
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__bhLqx
                    )}
                    href={`/new-page-7`}
                    target={"_blank"}
                    title={"1"}
                  >
                    {"Back"}
                  </a>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"loginButton"}
                  data-plasmic-override={overrides.loginButton}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.loginButton)}
                >
                  <div
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"Verify"}
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
            <a
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(projectcss.all, projectcss.a, sty.logo)}
              href={`/new-page-10`}
              target={"_blank"}
              title={"1"}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"logoUbc"}
                data-plasmic-override={overrides.logoUbc}
                hasGap={true}
                className={classNames(projectcss.all, sty.logoUbc)}
              >
                <div
                  data-plasmic-name={"frame3663"}
                  data-plasmic-override={overrides.frame3663}
                  className={classNames(projectcss.all, sty.frame3663)}
                >
                  <div
                    data-plasmic-name={"c"}
                    data-plasmic-override={overrides.c}
                    className={classNames(projectcss.all, sty.c)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jy0PI
                      )}
                    >
                      {"C"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"u"}
                    data-plasmic-override={overrides.u}
                    className={classNames(projectcss.all, sty.u)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ajNBn
                      )}
                    >
                      {"U"}
                    </div>
                  </div>
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ij0UG
                )}
              >
                {"UnBoxing Community"}
              </div>
            </a>
            <Stack__
              as={"div"}
              data-plasmic-name={"logo2"}
              data-plasmic-override={overrides.logo2}
              hasGap={true}
              className={classNames(projectcss.all, sty.logo2)}
            >
              <div
                data-plasmic-name={"logoUbc2"}
                data-plasmic-override={overrides.logoUbc2}
                className={classNames(projectcss.all, sty.logoUbc2)}
              >
                <div
                  data-plasmic-name={"c2"}
                  data-plasmic-override={overrides.c2}
                  className={classNames(projectcss.all, sty.c2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__auHbC
                    )}
                  >
                    {"C"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"u2"}
                  data-plasmic-override={overrides.u2}
                  className={classNames(projectcss.all, sty.u2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p5Cg7
                    )}
                  >
                    {"U"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pkweK
                )}
              >
                {"Back to\nUnBoxing"}
              </div>
            </Stack__>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__rffSh)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: image2FbzPv3GHmqLc,
                fullWidth: 922,
                fullHeight: 26,
                aspectRatio: undefined
              }}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "otp",
    "joinAThrivingCommunityOfEngineers",
    "frame3664",
    "checkBox",
    "weHaveSentYouA4DigitOtp",
    "checkBox2",
    "otp2",
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "passwordHideAndSee",
    "svg",
    "frame3665",
    "checkBox3",
    "loginButton",
    "button",
    "logo",
    "logoUbc",
    "frame3663",
    "c",
    "u",
    "logo2",
    "logoUbc2",
    "c2",
    "u2"
  ],

  otp: [
    "otp",
    "joinAThrivingCommunityOfEngineers",
    "frame3664",
    "checkBox",
    "weHaveSentYouA4DigitOtp",
    "checkBox2",
    "otp2",
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "passwordHideAndSee",
    "svg",
    "frame3665",
    "checkBox3",
    "loginButton",
    "button",
    "logo",
    "logoUbc",
    "frame3663",
    "c",
    "u",
    "logo2",
    "logoUbc2",
    "c2",
    "u2"
  ],

  joinAThrivingCommunityOfEngineers: ["joinAThrivingCommunityOfEngineers"],
  frame3664: [
    "frame3664",
    "checkBox",
    "weHaveSentYouA4DigitOtp",
    "checkBox2",
    "otp2",
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "passwordHideAndSee",
    "svg",
    "frame3665",
    "checkBox3",
    "loginButton",
    "button"
  ],

  checkBox: ["checkBox", "weHaveSentYouA4DigitOtp", "checkBox2"],
  weHaveSentYouA4DigitOtp: ["weHaveSentYouA4DigitOtp"],
  checkBox2: ["checkBox2"],
  otp2: [
    "otp2",
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "passwordHideAndSee",
    "svg"
  ],

  frame3666: [
    "frame3666",
    "label",
    "frame3667",
    "frame3752",
    "passwordHideAndSee",
    "svg"
  ],

  label: ["label"],
  frame3667: ["frame3667", "frame3752", "passwordHideAndSee", "svg"],
  frame3752: ["frame3752"],
  passwordHideAndSee: ["passwordHideAndSee", "svg"],
  svg: ["svg"],
  frame3665: ["frame3665", "checkBox3", "loginButton", "button"],
  checkBox3: ["checkBox3"],
  loginButton: ["loginButton", "button"],
  button: ["button"],
  logo: ["logo", "logoUbc", "frame3663", "c", "u"],
  logoUbc: ["logoUbc", "frame3663", "c", "u"],
  frame3663: ["frame3663", "c", "u"],
  c: ["c"],
  u: ["u"],
  logo2: ["logo2", "logoUbc2", "c2", "u2"],
  logoUbc2: ["logoUbc2", "c2", "u2"],
  c2: ["c2"],
  u2: ["u2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOtp__ArgProps,
          internalVariantPropNames: PlasmicOtp__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOtp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOtp";
  } else {
    func.displayName = `PlasmicOtp.${nodeName}`;
  }
  return func;
}

export const PlasmicOtp = Object.assign(
  // Top-level PlasmicOtp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    otp: makeNodeComponent("otp"),
    joinAThrivingCommunityOfEngineers: makeNodeComponent(
      "joinAThrivingCommunityOfEngineers"
    ),
    frame3664: makeNodeComponent("frame3664"),
    checkBox: makeNodeComponent("checkBox"),
    weHaveSentYouA4DigitOtp: makeNodeComponent("weHaveSentYouA4DigitOtp"),
    checkBox2: makeNodeComponent("checkBox2"),
    otp2: makeNodeComponent("otp2"),
    frame3666: makeNodeComponent("frame3666"),
    label: makeNodeComponent("label"),
    frame3667: makeNodeComponent("frame3667"),
    frame3752: makeNodeComponent("frame3752"),
    passwordHideAndSee: makeNodeComponent("passwordHideAndSee"),
    svg: makeNodeComponent("svg"),
    frame3665: makeNodeComponent("frame3665"),
    checkBox3: makeNodeComponent("checkBox3"),
    loginButton: makeNodeComponent("loginButton"),
    button: makeNodeComponent("button"),
    logo: makeNodeComponent("logo"),
    logoUbc: makeNodeComponent("logoUbc"),
    frame3663: makeNodeComponent("frame3663"),
    c: makeNodeComponent("c"),
    u: makeNodeComponent("u"),
    logo2: makeNodeComponent("logo2"),
    logoUbc2: makeNodeComponent("logoUbc2"),
    c2: makeNodeComponent("c2"),
    u2: makeNodeComponent("u2"),
    // Metadata about props expected for PlasmicOtp
    internalVariantProps: PlasmicOtp__VariantProps,
    internalArgProps: PlasmicOtp__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicOtp;
/* prettier-ignore-end */
